/**
 * Generic Secret Pattern Detection Rules
 *
 * Rules for detecting generic API keys, tokens, and service-specific secrets
 */

import type { Rule } from '../types';

export const genericSecretRules: Rule[] = [
  {
    id: 'SEC-GEN-001',
    name: 'Generic API Key Assignment',
    description: 'Detects hardcoded values assigned to API key variables',
    category: 'security',
    severity: 'critical',
    languages: ['javascript', 'typescript', 'jsx', 'tsx'],
    pattern: '(api[_-]?key|apikey)\\s*[=:]\\s*["\'][A-Za-z0-9_\\-]{16,}["\']',
    patternFlags: 'gi',
    message: 'Hardcoded API key detected.',
    remediation: 'Use environment variables: process.env.API_KEY',
    enabled: true,
  },
  {
    id: 'SEC-GEN-002',
    name: 'Generic Secret Assignment',
    description: 'Detects hardcoded values assigned to secret variables',
    category: 'security',
    severity: 'critical',
    languages: ['javascript', 'typescript', 'jsx', 'tsx'],
    pattern: '(secret|secret[_-]?key)\\s*[=:]\\s*["\'][A-Za-z0-9_\\-]{8,}["\']',
    patternFlags: 'gi',
    message: 'Hardcoded secret detected.',
    remediation: 'Use environment variables or a secrets manager.',
    enabled: true,
  },
  {
    id: 'SEC-GEN-003',
    name: 'Generic Token Assignment',
    description: 'Detects hardcoded values assigned to token variables',
    category: 'security',
    severity: 'critical',
    languages: ['javascript', 'typescript', 'jsx', 'tsx'],
    pattern: '(access[_-]?token|auth[_-]?token|bearer[_-]?token)\\s*[=:]\\s*["\'][A-Za-z0-9_\\-.]{20,}["\']',
    patternFlags: 'gi',
    message: 'Hardcoded access token detected.',
    remediation: 'Tokens should be obtained at runtime, not hardcoded.',
    enabled: true,
  },
  {
    id: 'SEC-GEN-004',
    name: 'JWT Token',
    description: 'Detects hardcoded JWT tokens',
    category: 'security',
    severity: 'critical',
    languages: ['javascript', 'typescript', 'jsx', 'tsx', 'html'],
    pattern: 'eyJ[A-Za-z0-9_-]{10,}\\.eyJ[A-Za-z0-9_-]{10,}\\.[A-Za-z0-9_-]{10,}',
    patternFlags: 'g',
    message: 'JWT token detected. JWTs contain encoded data and should not be hardcoded.',
    remediation: 'JWTs should be obtained at runtime through authentication flows.',
    enabled: true,
  },
  {
    id: 'SEC-GEN-005',
    name: 'Bearer Token in Header',
    description: 'Detects hardcoded Bearer tokens in HTTP headers',
    category: 'security',
    severity: 'critical',
    languages: ['javascript', 'typescript', 'jsx', 'tsx'],
    pattern: '["\']Authorization["\']\\s*:\\s*["\']Bearer\\s+[A-Za-z0-9_\\-.]+["\']',
    patternFlags: 'gi',
    message: 'Hardcoded Bearer token in Authorization header.',
    remediation: 'Get the token from secure storage at runtime.',
    enabled: true,
  },
  {
    id: 'SEC-GEN-006',
    name: 'Stripe API Key',
    description: 'Detects Stripe API keys',
    category: 'security',
    severity: 'critical',
    languages: ['javascript', 'typescript', 'jsx', 'tsx', 'html', 'csharp'],
    pattern: 'sk_(live|test)_[A-Za-z0-9]{24,}',
    patternFlags: 'g',
    message: 'Stripe Secret Key detected.',
    remediation: 'Use environment variables for Stripe keys.',
    enabled: true,
  },
  {
    id: 'SEC-GEN-007',
    name: 'Stripe Publishable Key (Live)',
    description: 'Detects Stripe live publishable keys that may indicate production exposure',
    category: 'security',
    severity: 'warning',
    languages: ['javascript', 'typescript', 'jsx', 'tsx', 'html'],
    pattern: 'pk_live_[A-Za-z0-9]{24,}',
    patternFlags: 'g',
    message: 'Stripe Live Publishable Key detected. Ensure this is intentional.',
    remediation: 'Consider using environment variables even for publishable keys.',
    enabled: true,
  },
  {
    id: 'SEC-GEN-008',
    name: 'SendGrid API Key',
    description: 'Detects SendGrid API keys',
    category: 'security',
    severity: 'critical',
    languages: ['javascript', 'typescript', 'jsx', 'tsx', 'html', 'csharp'],
    pattern: 'SG\\.[A-Za-z0-9_-]{22}\\.[A-Za-z0-9_-]{43}',
    patternFlags: 'g',
    message: 'SendGrid API Key detected.',
    remediation: 'Use environment variables for SendGrid keys.',
    enabled: true,
  },
  {
    id: 'SEC-GEN-009',
    name: 'Twilio Account SID',
    description: 'Detects Twilio Account SID patterns',
    category: 'security',
    severity: 'critical',
    languages: ['javascript', 'typescript', 'jsx', 'tsx', 'html', 'csharp'],
    pattern: 'AC[a-f0-9]{32}',
    patternFlags: 'g',
    message: 'Twilio Account SID detected.',
    remediation: 'Use environment variables for Twilio credentials.',
    enabled: true,
  },
  {
    id: 'SEC-GEN-010',
    name: 'Google API Key',
    description: 'Detects Google API keys',
    category: 'security',
    severity: 'critical',
    languages: ['javascript', 'typescript', 'jsx', 'tsx', 'html'],
    pattern: 'AIza[A-Za-z0-9_-]{35}',
    patternFlags: 'g',
    message: 'Google API Key detected.',
    remediation: 'Restrict the API key in Google Cloud Console and use environment variables.',
    enabled: true,
  },
];

/**
 * Export function to get generic secret rules
 */
export function getGenericSecretRules(): Rule[] {
  return genericSecretRules;
}
